from enum import Enum


class DroneStatus(str, Enum):
    IDLE = "idle"
    PLANNING = "planning"
    FLYING = "flying"
    REROUTING = "rerouting"
    CHARGING = "charging"
    PAUSED = "paused"
    SUCCESS = "success"
    FAILED = "failed"
    EMERGENCY_LANDING = "emergency_landing"


class OrderStatus(str, Enum):
    PENDING = "pending"
    ASSIGNED = "assigned"
    GOING_TO_PICKUP = "going_to_pickup"
    PICKED_UP = "picked_up"
    DELIVERING = "delivering"
    COMPLETED = "completed"
    FAILED = "failed"
    CANCELED = "canceled"


class MissionStatus(str, Enum):
    PLANNED = "planned"
    TO_PICKUP = "to_pickup"
    PICKUP_ARRIVED = "pickup_arrived"
    TO_DROPOFF = "to_dropoff"
    COMPLETED = "completed"
    FAILED = "failed"


class EventLevel(str, Enum):
    INFO = "info"
    WARNING = "warning"
    ERROR = "error"
    SUCCESS = "success"


class EventCode(str, Enum):
    PATH_PLANNED = "PATH_PLANNED"
    PATH_REPLANNED = "PATH_REPLANNED"
    OBSTACLE_ADDED = "OBSTACLE_ADDED"
    OBSTACLE_DETECTED = "OBSTACLE_DETECTED"
    NO_FLY_ZONE_ADDED = "NO_FLY_ZONE_ADDED"
    NO_FLY_ZONE_REPLAN = "NO_FLY_ZONE_REPLAN"
    NO_FLY_ZONE_REPLAN_FAILED = "NO_FLY_ZONE_REPLAN_FAILED"
    WEATHER_CHANGED = "WEATHER_CHANGED"
    CHARGING_STARTED = "CHARGING_STARTED"
    CHARGING_COMPLETED = "CHARGING_COMPLETED"
    EMERGENCY_LANDING = "EMERGENCY_LANDING"
    DELIVERY_SUCCESS = "DELIVERY_SUCCESS"
    DELIVERY_FAILED = "DELIVERY_FAILED"
    SIMULATION_PAUSED = "SIMULATION_PAUSED"
    SIMULATION_RESUMED = "SIMULATION_RESUMED"
    SIMULATION_STOPPED = "SIMULATION_STOPPED"
    DRONE_PROXIMITY_WARNING = "DRONE_PROXIMITY_WARNING"
    ORDER_BATCH_RECEIVED = "ORDER_BATCH_RECEIVED"
    ORDER_ACCEPTED = "ORDER_ACCEPTED"
    ORDER_REJECTED = "ORDER_REJECTED"
    ORDER_STATE_UPDATED = "ORDER_STATE_UPDATED"
    MISSION_CREATED = "MISSION_CREATED"
    DISPATCH_STARTED = "DISPATCH_STARTED"
    DISPATCH_ASSIGNED = "DISPATCH_ASSIGNED"
    DISPATCH_NO_DRONE_AVAILABLE = "DISPATCH_NO_DRONE_AVAILABLE"
    DISPATCH_FAILED = "DISPATCH_FAILED"
    MISSION_STARTED = "MISSION_STARTED"
    MISSION_TO_PICKUP = "MISSION_TO_PICKUP"
    PICKUP_ARRIVED = "PICKUP_ARRIVED"
    PACKAGE_PICKED_UP = "PACKAGE_PICKED_UP"
    MISSION_TO_DROPOFF = "MISSION_TO_DROPOFF"
    DROPOFF_ARRIVED = "DROPOFF_ARRIVED"
    ORDER_COMPLETED = "ORDER_COMPLETED"
    ORDER_FAILED = "ORDER_FAILED"
    MISSION_FAILED = "MISSION_FAILED"
    WORKER_ERROR = "WORKER_ERROR"
